_BASE_: ../default.yaml
exp_name: tci_fmc_knee_patho=0_16x_loupe-roi-warmup_1e-3
init_exp_dir: results/tci_fmc_knee_patho=0_16x_loupe-full_1e-2
init_modules: [sampler, reconstructor]
init_module_trainability: [True, True]
lr: 0.001
model:
  name: LOUPE-RoI-Warmup
  sampler:
    name: LOUPESampler
    shape: [192, 192]
    subsampling_dim: [-2, -1]
    acceleration: 16
    line_constrained: False
    preselect_num: 0
    preselect_ratio: 128
  reconstructor:
    name: UNetMonaiReconstructor
    spatial_dims: 2
    in_channels: 1
    out_channels: 1
    channels: [64, 128, 256, 512, 1024]
    strides: [2, 2, 2, 2]
    norm: True
