_BASE_: ../default.yaml
exp_name: tci_fmc_knee_patho=0_16x_loupe-roi_1e-2
lr: 0.01
model:
  name: LOUPE-RoI
  sampler:
    name: LOUPESampler
    shape: [192, 192]
    subsampling_dim: [-2, -1]
    acceleration: 16
    line_constrained: False
    preselect_num: 0
    preselect_ratio: 128
  reconstructor:
    name: UNetMonaiReconstructor
    spatial_dims: 2
    in_channels: 1
    out_channels: 1
    channels: [64, 128, 256, 512, 1024]
    strides: [2, 2, 2, 2]
    norm: True
