_BASE_: ../default.yaml
exp_name: tci_brats_flair_label=wt_16x_loupe-cls-fixed_1e-4
init_exp_dir: results/tci_brats_flair_label=wt_16x_loupe-recon_1e-2
init_modules: [sampler, reconstructor]
init_module_trainability: [False, False]
lr: 0.0001
model:
  name: LOUPE-cls-Fixed
  sampler:
    name: LOUPESampler
    shape: [240, 240]
    subsampling_dim: [-2, -1]
    acceleration: 16
    line_constrained: False
    preselect_num: 0
    preselect_ratio: 128
  reconstructor:
    name: UNetMonaiReconstructor
    spatial_dims: 2
    in_channels: 1
    out_channels: 1
    channels: [64, 128, 256, 512, 1024]
    strides: [2, 2, 2, 2]
    norm: True
  predictor:
    name: ResNet18Classifier
    in_chans: 1
    num_classes: 2
train_loss:
  name: CrossEntropyLoss
val_test_loss:
  name: ClassificationAccuracy