_BASE_: ../default.yaml
exp_name: tci_oasis2d_label=-1_64x_poissonc-unet-recon_1e-2
task: recon
lr: 0.01
model:
  name: PoissonC-UNet-Recon
  sampler:
    name: PoissonSampler
    shape: [192, 160]
    subsampling_dim: [-2, -1]
    acceleration: 64
  reconstructor:
    name: UNetMonaiReconstructor
    spatial_dims: 2
    in_channels: 1
    out_channels: 1
    channels: [64, 128, 256, 512, 1024]
    strides: [2, 2, 2, 2]
    norm: True
  predictor:
    name: IdentityPredictor
train_loss:
  name: PSNRLoss
val_test_loss:
  name: PSNR