_BASE_: ../default.yaml
exp_name: tci_oasis2d_label=-1_64x_loupe-bigunet-seg-scratch_1e-2
lr: 0.01
model:
  name: LOUPE-BigUNet-Seg-Finetuned
  sampler:
    name: LOUPESampler
    shape: [192, 160]
    subsampling_dim: [-2, -1]
    acceleration: 64
    line_constrained: False
    preselect_num: 0
    preselect_ratio: 512
  reconstructor:
    name: ZeroFilledReconstructor
  predictor:
    name: UNetMonaiSegmenter
    spatial_dims: 2
    in_channels: 1
    out_channels: 5
    channels: [128, 256, 512, 1024, 2048]
    strides: [2, 2, 2, 2]