_BASE_: ../default.yaml
exp_name: tci_oasis2d_label=-1_64x_tacklenew-seg-scratch_1e-3
lr: 0.001
model:
  name: TackleNew-Seg-Scratch
  sampler: 
    name: LOUPESampler
    shape: [192, 160]
    subsampling_dim: [-2, -1]
    acceleration: 64
    line_constrained: False
    preselect_num: 0
    preselect_ratio: 512
  reconstructor:
    name: VarNetReconstructor
    num_cascades: 12
    chans: 18
    pools: 4
    acs_ratio: 512
    dc_weight: 1
    adj_dc_weight: True
  predictor:
    name: UNetMonaiSegmenter
    spatial_dims: 2
    in_channels: 1
    out_channels: 5
    channels: [64, 128, 256, 512, 1024]
    strides: [2, 2, 2, 2]