_BASE_: ../default.yaml
exp_name: tci_skmtea_label=-1_64x_poissonc-unet-seg-ft_1e-3
init_exp_dir: results/tci_skmtea_label=-1_64x_poissonc-unet-recon_1e-3
init_modules: [sampler, reconstructor]
init_module_trainability: [True, True]
lr: 0.001
model:
  name: PoissonC-UNet-Seg-Finetuned
  sampler:
    name: PoissonSampler
    shape: [512, 512]
    subsampling_dim: [-2, -1]
    acceleration: 64
  reconstructor:
    name: UNetMonaiReconstructor
    spatial_dims: 2
    in_channels: 1
    out_channels: 1
    channels: [64, 128, 256, 512, 1024]
    strides: [2, 2, 2, 2]
    norm: True
  predictor:
    name: UNetMonaiSegmenter
    spatial_dims: 2
    in_channels: 1
    out_channels: 5
    channels: [64, 128, 256, 512, 1024]
    strides: [2, 2, 2, 2]