_BASE_: ../default.yaml
exp_name: tci_skmtea_label=-1_64x_loupe-recon_1e-3
task: recon
lr: 0.001
model:
  name: LOUPE-Recon
  sampler:
    name: LOUPESampler
    shape: [512, 512]
    subsampling_dim: [-2, -1]
    acceleration: 64
    line_constrained: False
    preselect_num: 0
    preselect_ratio: 512
  reconstructor:
    name: UNetMonaiReconstructor
    spatial_dims: 2
    in_channels: 1
    out_channels: 1
    channels: [64, 128, 256, 512, 1024]
    strides: [2, 2, 2, 2]
    norm: True
  predictor:
    name: IdentityPredictor
train_loss:
  name: PSNRLoss
val_test_loss:
  name: PSNR