_BASE_: ../default.yaml
exp_name: tci_skmtea_label=-1_64x_tacklenew-seg-fixed_1e-4
init_exp_dir: results/tci_skmtea_label=-1_64x_tacklenew-recon_1e-3
init_modules: [sampler, reconstructor]
init_module_trainability: [False, False]
lr: 0.0001
model:
  name: TackleNew-Seg-Fixed
  sampler:
    name: LOUPESampler
    shape: [512, 512]
    subsampling_dim: [-2, -1]
    acceleration: 64
    line_constrained: False
    preselect_num: 0
    preselect_ratio: 512
  reconstructor:
    name: VarNetReconstructor
    num_cascades: 12
    chans: 18
    pools: 4
    acs_ratio: 512
    dc_weight: 1
    adj_dc_weight: True
  predictor:
    name: UNetMonaiSegmenter
    spatial_dims: 2
    in_channels: 1
    out_channels: 5
    channels: [64, 128, 256, 512, 1024]
    strides: [2, 2, 2, 2]