_BASE_: ../default2.yaml
exp_name: "novarnet-recon_16x_2-cascade_ks[3,4]_rc0.02_fix_idk"
task: recon
lr: 0.001
model:
  name: NOVarnet-Recon
  sampler:
    name: LOUPESampler
    shape: [512, 512]
    subsampling_dim: [-2, -1]
    acceleration: 16
    line_constrained: False
    preselect_num: 0
    preselect_ratio: 128
  reconstructor:
    name: NOVarnet
    num_cascades: 2
    sens_chans: 8
    sens_pools: 4
    chans: 18
    pools: 4
    acs_ratio: 128
    use_dc_term: True
    kernel_shape: [3, 4]
    radius_cutoff: 0.02 
  predictor:
    name: IdentityPredictor
train_loss:
  name: PSNRLoss
val_test_loss:
  name: PSNR