_BASE_: ../default.yaml
exp_name: "novarnet_16x_2-cascade_ks[3,4]_rc0.02_seg-ft"
init_exp_dir: "results/novarnet-recon_16x_2-cascade_ks[3,4]_rc0.02_final"
init_modules: [sampler, reconstructor]
init_module_trainability: [True, True]
lr: 0.001
model:
  name: NOVarnet-Seg-Finetuned
  sampler: 
    name: LOUPESampler
    shape: [512, 512]
    subsampling_dim: [-2, -1]
    acceleration: 16
    line_constrained: False
    preselect_num: 0
    preselect_ratio: 128
  reconstructor:
    name: NOVarnet
    num_cascades: 2
    sens_chans: 8
    sens_pools: 4
    chans: 18
    pools: 4
    acs_ratio: 32
    use_dc_term: True
    kernel_shape: [3, 4]
    radius_cutoff: 0.02
  predictor:
    name: UNetMonaiSegmenter
    spatial_dims: 2
    in_channels: 1
    out_channels: 5
    channels: [64, 128, 256, 512, 1024]
    strides: [2, 2, 2, 2]