_BASE_: ../default.yaml
exp_name: tci_fmc_knee_patho=0_8x_center-varnetnew_1e-2
lr: 0.01
model:
  name: Center-VarNetNew
  sampler:
    name: CenterSampler
    shape: [192, 192]
    subsampling_dim: [-2, -1]
    acceleration: 8
    line_constrained: False
  reconstructor:
    name: VarNetReconstructor
    num_cascades: 12
    chans: 18
    pools: 4
    acs_ratio: 64
    dc_weight: 1
    adj_dc_weight: True
train_loss:
  name: PSNRLoss
