_BASE_: ../default.yaml
exp_name: tci_fsc_knee_patho=0_16x_poissonc-unet_1e-2
lr: 0.01
model:
  name: PoissonC-UNet
  sampler:
    name: PoissonSampler
    shape: [192, 192]
    subsampling_dim: [-2, -1]
    acceleration: 16
  reconstructor:
    name: UNetMonaiReconstructor
    spatial_dims: 2
    in_channels: 1
    out_channels: 1
    channels: [64, 128, 256, 512, 1024]
    strides: [2, 2, 2, 2]
    norm: True
train_loss:
  name: PSNRLoss
