_BASE_: ../default.yaml
exp_name: "e2evarnet_multi-rate_recon"
task: recon
lr: 0.001
model:
  name: E2EVarnet-Recon
  sampler:
    name: LoupeSamplerMultiAcceleration
    shape: [512, 512]
    subsampling_dim: [-2, -1]
    accelerations: [4,8,16,32,64]
    line_constrained: False
    preselect_ratios: [32, 64, 128, 256, 512]
  reconstructor:
    name: VarNetReconstructor
    num_cascades: 2
    chans: 18
    pools: 4
    dc_weight: 1
    adj_dc_weight: True
  predictor:
    name: IdentityPredictor
train_loss:
  name: PSNRLoss
val_test_loss:
  name: PSNR