_BASE_: ../default.yaml
exp_name: "e2evarnet_multi-rate_seg-fixed"
init_exp_dir: "results/e2evarnet_multi-rate_recon"
init_modules: [sampler, reconstructor]
init_module_trainability: [False, False]
lr: 0.0001
model:
  name: E2EVarnet-Seg
  sampler:
    name: LoupeSamplerMultiAcceleration
    shape: [512, 512]
    subsampling_dim: [-2, -1]
    accelerations: [4,8,16,32,64]
    line_constrained: False
    preselect_ratios: [32, 64, 128, 256, 512]
  reconstructor:
    name: VarNetReconstructor
    num_cascades: 2
    chans: 18
    pools: 4
    dc_weight: 1
    adj_dc_weight: True
  predictor:
    name: UNetMonaiSegmenter
    spatial_dims: 2
    in_channels: 1
    out_channels: 5
    channels: [64, 128, 256, 512, 1024]
    strides: [2, 2, 2, 2]