_BASE_: ../../default.yaml
exp_name: tacklenew_16x_2-cascade_recon-ft_8x
task: recon
init_exp_dir: results/tacklenew-recon_16x_2-cascade
init_modules: [sampler, reconstructor]
init_module_trainability: [True, True]
lr: 0.001
model:
  name: TackleNew-Recon-Finetuned
  sampler:
    name: LOUPESampler
    shape: [512, 512]
    subsampling_dim: [-2, -1]
    acceleration: 8
    line_constrained: False
    preselect_num: 0
    preselect_ratio: 64
  reconstructor:
    name: VarNetReconstructor
    num_cascades: 2
    chans: 18
    pools: 4
    acs_ratio: 64
    dc_weight: 1
    adj_dc_weight: True
  predictor:
    name: IdentityPredictor
train_loss:
  name: PSNRLoss
val_test_loss:
  name: PSNR