_BASE_: ../default.yaml
exp_name: tci_oasis2d_label=-1_16x_tacklenew-recon-task-mask_1e-2
init_exp_dir: results/tci_oasis2d_label=-1_16x_tacklenew-seg-ft_1e-3
init_modules: [sampler]
init_module_trainability: [False]
task: recon
lr: 0.01
model:
  name: TackleNew-Recon-Task-Mask
  sampler:
    name: LOUPESampler
    shape: [192, 160]
    subsampling_dim: [-2, -1]
    acceleration: 16
    line_constrained: False
    preselect_num: 0
    preselect_ratio: 128
  reconstructor:
    name: VarNetReconstructor
    num_cascades: 12
    chans: 18
    pools: 4
    acs_ratio: 128
    dc_weight: 1
    adj_dc_weight: True
  predictor:
    name: IdentityPredictor
train_loss:
  name: PSNRLoss
val_test_loss:
  name: PSNR