exp_name: brats_flair_label=wt
procedure:
  name: TrainValTest
task: cls
trainer:
  max_epochs: 1000
patience: 10
callbacks: [TestCallback, PaperFigureCallback]
lr: 0.0001
logger:
  project: mri_codesign
data_module:
  name: BratsDataModule
  shape: [240, 240]
  noise_std: 0.0005
  batch_size: 16
  selected_modality: flair
  selected_class: 2 # whole tumor
vis_freq: 2000
model:
  name: TBD
  sampler:
    name: TBD
  reconstructor:
    name: TBD
  predictor:
    name: TBD
train_loss:
  name: TBD
val_test_loss:
  name: TBD
