_BASE_: ../default.yaml
exp_name: tacklenew-recon_16x_2-cascade_seg-fixed
init_exp_dir: results/tacklenew-recon_16x_2-cascade_final
init_modules: [sampler, reconstructor]
init_module_trainability: [False, False]
lr: 0.0001
model:
  name: TackleNew-Seg-Fixed
  sampler:
    name: LOUPESampler
    shape: [512, 512]
    subsampling_dim: [-2, -1]
    acceleration: 16
    line_constrained: False
    preselect_num: 0
    preselect_ratio: 128
  reconstructor:
    name: VarNetReconstructor
    num_cascades: 2
    chans: 18
    pools: 4
    acs_ratio: 128
    dc_weight: 1
    adj_dc_weight: True
  predictor:
    name: UNetMonaiSegmenter
    spatial_dims: 2
    in_channels: 1
    out_channels: 5
    channels: [64, 128, 256, 512, 1024]
    strides: [2, 2, 2, 2]