_BASE_: ../default.yaml
exp_name: tci_brats_flair_label=wt_64x_poissonc-unet-recon_1e-2
callbacks: [TestCallback, PaperFigureCallback]
task: recon
lr: 0.01
model:
  name: PoissonC-UNet-Recon
  sampler:
    name: PoissonSampler
    shape: [240, 240]
    subsampling_dim: [-2, -1]
    acceleration: 64
  reconstructor:
    name: UNetMonaiReconstructor
    spatial_dims: 2
    in_channels: 1
    out_channels: 1
    channels: [64, 128, 256, 512, 1024]
    strides: [2, 2, 2, 2]
    norm: True
  predictor:
    name: IdentityPredictor
train_loss:
  name: PSNRLoss
val_test_loss:
  name: PSNR